#!/usr/bin/env python3
# my comment

"""
This module connects to MongoDB and switches to or creates a database named 'my_db'.
"""

from pymongo import MongoClient

def get_my_db():
    """
    Connects to MongoDB and returns the 'my_db' database.
    """
    client = MongoClient('mongodb://127.0.0.1:27017')
    my_db = client['my_db']
    print("switched to db my_db")
    return my_db

if __name__ == "__main__":
    get_my_db()
